name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install -e ".[docs]"
      - run: pip install -e ".[dev]"
      - run: mkdocs gh-deploy --force
      - run: python -m unittest

  post_success:
    runs-on: ubuntu-latest
    steps:
    - name: if_push
      if: ${{ github.event_name == 'push' }}
      run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{
            "text": "New push to repo. Latest commit message: ${{ github.event.head_commit.message }}"
          }' ${{ secrets.WEBHOOK_URL }}
    - name: if_pull_request
      if: ${{ github.event_name == 'pull_request' }}
      run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{
            "text": "New pull request at: ${{ github.event.pull_request.html_url }}"
          }' ${{ secrets.WEBHOOK_URL }}
